<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_drive_robot">
  
  
    <!-- ros_control plugin -->
    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/ddr</robotNamespace>
        <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
      </plugin>
    </gazebo>
    
    
    <!--
        Differential Drive
    -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>30.0</updateRate>
            <leftJoint>left_wheel_joint</leftJoint>
            <rightJoint>right_wheel_joint</rightJoint>
            <wheelSeparation>${chassis_radius * 1.5}</wheelSeparation>
            <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
            <torque>20</torque>
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <robotBaseFrame>base_footprint</robotBaseFrame>
        </plugin>
    </gazebo>
  
  
    <!--
        Camera Sensor
    -->
    <gazebo reference="${camera_name}">
        <sensor type="depth" name="openni_camera_camera">       
            <always_on>1</always_on>
            <visualize>true</visualize>             
            <camera>
                <horizontal_fov>1.047</horizontal_fov>  
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <depth_camera>
    
                </depth_camera>
                <clip>
                    <near>0.1</near>
                    <far>100</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
                <alwaysOn>true</alwaysOn>
                    <updateRate>10.0</updateRate>
                    <cameraName>camera</cameraName>
                    <frameName>openni_camera_link</frameName>                   
                <imageTopicName>rgb/image_raw</imageTopicName>
                <depthImageTopicName>depth/image_raw</depthImageTopicName>
                <pointCloudTopicName>depth/points</pointCloudTopicName>
                <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>              
                <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>            
                <pointCloudCutoff>0.4</pointCloudCutoff>                
                    <hackBaseline>0.07</hackBaseline>
                    <distortionK1>0.0</distortionK1>
                    <distortionK2>0.0</distortionK2>
                    <distortionK3>0.0</distortionK3>
                    <distortionT1>0.0</distortionT1>
                    <distortionT2>0.0</distortionT2>
                <CxPrime>0.0</CxPrime>
                <Cx>0.0</Cx>
                <Cy>0.0</Cy>
                <focalLength>0.0</focalLength>
                </plugin>
        </sensor>
    </gazebo>
    
    
    <gazebo reference="${camera_name}">
        <sensor type="camera" name="${camera_name}_sensor">
            <update_rate>30.0</update_rate>
            <camera name="${camera_name}_camera">
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>800</width>
                    <height>800</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.02</near>
                    <far>300</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                 <stddev>0.007</stddev>
                </noise>
            </camera>
            <!--
            <plugin name="$camera_controller" filename="libgazebo_ros_openni_kinect.so">
                <baseline>0.2</baseline>
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>ddr/${camera_name}</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <depthImageTopicName>depth_image/</depthImageTopicName>
                <depthImageInfoTopicName>depth_info/</depthImageInfoTopicName>
                <pointCloudTopicName>point_cloud/</pointCloudTopicName>
                <frameName>${camera_name}</frameName>
                <pointCloudCutoff>0.5</pointCloudCutoff>
                <distortionK1>0.00000001</distortionK1>
                <distortionK2>0.00000001</distortionK2>
                <distortionK3>0.00000001</distortionK3>
                <distortionT1>0.00000001</distortionT1>
                <distortionT2>0.00000001</distortionT2>
                <CxPrime>0</CxPrime>
                <Cx>0</Cx>
                <Cy>0</Cy>
                <focalLength>0</focalLength>
                <hackBaseline>0</hackBaseline>
            </plugin>
            -->
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>ddr/${camera_name}</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>${camera_name}</frameName>
                <hackBaseline>0.07</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
            </plugin>
        </sensor>
    </gazebo>
    
  
    <!--
        Colors
        http://wiki.ros.org/simulator_gazebo/Tutorials/ListOfMaterials
    -->
    <xacro:macro name="gz_black_material" params="name">
        <gazebo reference="${name}">
            <material>Gazebo/FlatBlack</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="gz_white_material" params="name">
        <gazebo reference="${name}">
            <material>Gazebo/White</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="gz_blue_material" params="name">
        <gazebo reference="${name}">
            <material>Gazebo/Blue</material>
        </gazebo>
    </xacro:macro>
    
    <xacro:macro name="gz_red_material" params="name">
        <gazebo reference="${name}">
            <material>Gazebo/Red</material>
        </gazebo>
    </xacro:macro>
  
</robot>