<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_drive_robot">
    
    
    <!--Include Files-->
    <xacro:include filename="$(find lab03_description)/urdf/ddr.parameters.xacro" />
    <xacro:include filename="$(find lab03_description)/urdf/ddr.macros.xacro" />
    <xacro:include filename="$(find lab03_description)/urdf/ddr.materials.xacro" />
    
    <!--                Arguments
        <xacro:arg name="chassis_radius" default="0" />
        <xacro:arg name="chassis_height" default="0" />
        <xacro:arg name="wheel_radius"   default="0" />
        <xacro:arg name="glider_radius"  default="0" />
    -->
    
    <!--    -->
    <!--Build the robot!-->
    <!--    -->
    
    <!--Base Link-->
    <link name="base_link" />
    
    <!--Create the chassis and add it to the base link-->
    <link name="robot_chassis">
        <visual>
            <xacro:chassis_geometry />
            <material name="white" />
        </visual>
        <collision>
            <xacro:chassis_geometry />
        </collision>
        <xacro:cylinder_inertial mass="${chassis_mass}"
                                 radius="${chassis_radius}"
                                 length="${chassis_height}"
                                 />
    </link>
    <joint name="robot_chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="robot_chassis"/>
        <origin xyz="0 0 ${wheel_radius * 1.33 + 0.01}"/>
    </joint>
    
    <!--Add Wheels-->
    <xacro:wheel name="right_wheel" rl_reflection="1" />
    <xacro:wheel name="left_wheel"  rl_reflection="-1" />
    
    Add Gliders
    <xacro:glider name="front_glider" fb_reflection="1" />
    <xacro:glider name="back_glider" fb_reflection="-1" />

    
</robot>