<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_drive_robot">
    
        
    <!--
        Macro for creating cylinder inertial
    -->
    <xacro:macro name="cylinder_inertial" params="mass radius length">
        <inertial>
            <mass value="${mass}" />
            <inertia
                ixx="${(1.0 / 12.0) * (3.0 * radius**2 + length**2) * mass}"
                iyy="${(1.0 / 12.0) * (3.0 * radius**2 + length**2) * mass}"
                izz="${(1.0 / 12.0) * radius**2 * mass}"
                ixy="0"
                ixz="0"
                iyz="0"
                />
        </inertial>
    </xacro:macro>
    
    <!--
        Macro for creating sphere inertial
    -->
    <xacro:macro name="sphere_inertial" params="mass radius">
        <inertial>
            <mass value="${mass}" />
            <inertia
                ixx="${(2.0 / 5.0) * radius**2 * mass}"
                iyy="${(2.0 / 5.0) * radius**2 * mass}"
                izz="${(2.0 / 5.0) * radius**2 * mass}"
                ixy="0"
                ixz="0"
                iyz="0"
                />
        </inertial>
    </xacro:macro>
    
    <!--
        Macro for creating cube inertial
    -->
    <xacro:macro name="cube_inertial" params="mass x y z">
        <inertial>
            <mass value="${mass}" />
            <inertia
                ixx="${(1.0 / 12.0) * (y**2 + z**2) * mass}"
                iyy="${(1.0 / 12.0) * (x**2 + z**2) * mass}"
                izz="${(1.0 / 12.0) * (y**2 + x**2) * mass}"
                ixy="0"
                ixz="0"
                iyz="0"
                />
        </inertial>
    </xacro:macro>
    
    
    <!--Chassis Macros-->
    <xacro:macro name="chassis_geometry">
        <geometry>
            <cylinder length="${chassis_height}" radius="${chassis_radius}" />
        </geometry>
    </xacro:macro>
    
    
    <!--Wheel Macro-->
    <xacro:macro name="wheel" params="name rl_reflection">
        <xacro:gz_black_material name="${name}" />v
        <link name="${name}">
            <visual>
                <origin xyz="0 0 0" rpy="0 1.571 0" />
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}" />
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}" />
                </geometry>
            </collision>
            <xacro:cylinder_inertial mass="${wheel_mass}"
                                     radius="${wheel_radius}"
                                     length="${wheel_width}"
                                     />
        </link>
        <joint name="${name}_joint" type="continuous">
            <parent link="${chassis_name}"/>
            <child link="${name}"/>
            <origin xyz="${rl_reflection * chassis_radius * 0.75} 0 ${wheel_radius * -0.33}"/>
            <axis xyz="1 0 0"/>
        </joint>
    </xacro:macro>
    
    
    <!--Glider Macro-->
    <xacro:macro name="glider" params="name fb_reflection">
        <xacro:gz_black_material name="${name}" />
        <link name="${name}">
            <visual>
                <geometry>
                    <sphere radius="${glider_radius}" />
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${glider_radius}" />
                </geometry>
            </collision>
            <xacro:sphere_inertial mass="${glider_mass}"
                                   radius="${glider_radius}"
                                   />
        </link>
        <joint name="${name}_joint" type="fixed">
            <parent link="${chassis_name}"/>
            <child link="${name}"/>
            <origin xyz="0 ${fb_reflection * 0.5} -0.09"/>
        </joint>
    </xacro:macro>
    
    <!--Camera Macro-->
    <xacro:macro name="camera" params="name">
        <xacro:gz_red_material name="${name}" />
        <link name="${name}">
            <visual>
                <geometry>
                    <box size="${camera_length} ${camera_width} ${camera_height}" />
                </geometry>
                <material name="red"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${camera_length} ${camera_width} ${camera_height}" />
                </geometry>
            </collision>
            <xacro:cube_inertial mass="${camera_mass}"
                                 x="${camera_length}"
                                 y="${camera_width}"
                                 z="${camera_height}"
                                 />
        </link>
        <joint name="${name}_joint" type="fixed">
            <parent link="${chassis_name}"/>
            <child link="${name}"/>
            <origin xyz="0 ${chassis_radius} ${(chassis_height / 2.0) + (camera_height / 2.0)}" />
        </joint>
    </xacro:macro>
    
    
</robot>